### ISSUE TITLE
AssertionError: d3m.primitive_interfaces.base.CallResult[d3m.container.list.List]

### ISSUE THREAD

**Issue by obouluh** [datamllab/tods#21]
### when i run example1.py
`import pandas as pd

from tods import schemas as schemas_utils
from tods.utils import generate_dataset, generate_problem, evaluate_pipeline

table_path = 'datasets/yahoo_sub_5.csv'
target_index = 6  # what column is the target
metric = 'F1_MACRO'  # F1 on both label 0 and 1

# Read data and generate dataset and problem
df = pd.read_csv(table_path)
dataset = generate_dataset(df, target_index)
problem_description = generate_problem(dataset, metric)

# Load the default pipeline
pipeline = schemas_utils.load_default_pipeline()

# Run the pipeline
pipeline_result = evaluate_pipeline(dataset, pipeline, metric)
`

### the result :
ssh://****/anaconda3/envs/tods/bin/python -u /home/****/tods/examples/example1.py
Not all provided hyper-parameters for the data preparation pipeline 79ce71bd-db96-494b-a455-14f2e2ac5040 were used: ['method', 'number_of_folds', 'randomSeed', 'shuffle', 'stratified']
Traceback (most recent call last):
  File "/home/****/tods/examples/example1.py", line 19, in <module>
    pipeline_result = evaluate_pipeline(dataset, pipeline, metric)
  File "/home/****/tods/tods/utils.py", line 86, in evaluate_pipeline
    data_preparation_params=data_preparation_params)
  File "/home/****/tods/src/axolotl/axolotl/backend/base.py", line 263, in evaluate_pipeline
    data_preparation_params=data_preparation_params, scoring_params=scoring_params, timeout=timeout
  File "/home/****/tods/src/axolotl/axolotl/backend/simple.py", line 166, in evaluate_pipeline_request
    volumes_dir=self.volumes_dir, scratch_dir=self.scratch_dir, runtime_environment=self.runtime_environment
  File "/home/****/tods/src/d3m/d3m/runtime.py", line 1530, in evaluate
    scratch_dir=scratch_dir, runtime_environment=runtime_environment,
  File "/home/****/tods/src/d3m/d3m/runtime.py", line 1488, in prepare_data
    scratch_dir=scratch_dir, environment=runtime_environment,
  File "/home/****/tods/src/d3m/d3m/runtime.py", line 236, in __init__
    self.pipeline.check(allow_placeholders=False, standard_pipeline=self.is_standard_pipeline)
  File "/home/****/tods/src/d3m/d3m/metadata/pipeline.py", line 1496, in check
    self._check(allow_placeholders, standard_pipeline, input_types)
  File "/home/****/tods/src/d3m/d3m/metadata/pipeline.py", line 1766, in _check
    assert issubclass(produce_type, base.CallResult), produce_type
AssertionError: d3m.primitive_interfaces.base.CallResult[d3m.container.list.List]

Process finished with exit code 1

**Comment by lhenry15** [comment]
Could you provide the d3m version that you installed? Thanks

**Comment by obouluh** [comment]
> Could you provide the d3m version that you installed? Thanks

![image](https://user-images.githubusercontent.com/22076064/106412445-c3e4a600-6482-11eb-9d2a-405c2deedcb1.png)

Maybe I should change the version..

**Comment by lhenry15** [comment]
Our backend is the version of 2020.06, we have fixed the version in the setup.py. You can clone the latest version in master branch, and do "pip install -e ." again. It should be able the install the correct version.

**Comment by obouluh** [comment]
It works.Thanks!!!
@lhenry15

**Comment by AlnetharyTamim** [comment]
Hey @lhenry15 I am facing the same error. I used the correct version of d3m which is `2020.05.18` by checking `d3m.__version__`. I am using python3.6 and venv as a virtual environment with pip version 19.3.1. 

```
Not all provided hyper-parameters for the data preparation pipeline 79ce71bd-db96-494b-a455-14f2e2ac5040 were used: ['method', 'number_of_folds', 'randomSeed', 'shuffle', 'stratified']
{'error': "[StepFailedError('Step 6 for pipeline "
          "384bbfab-4f6d-4001-9f90-684ea5681f5d failed.',)]",
 'method_called': 'evaluate',
 'pipeline': '<d3m.metadata.pipeline.Pipeline object at 0x7fdde588c2e8>',
 'status': 'ERRORED'}
```
