### ISSUE TITLE
AttributeError: module 'typing' has no attribute 'GenericMeta'

### ISSUE THREAD

**Issue by billpwchan** [datamllab/tods#38]
I've tried to run the demo code in the README.md right after a clean install, and here is the issue I faced. Is there anyone who has a similar issue to run the sample code?

![image](https://user-images.githubusercontent.com/25129943/117877945-1c56eb00-b29d-11eb-8683-7708d6246c8b.png)

**Comment by lhenry15** [comment]
Could you provide the version of your "typing"?

**Comment by billpwchan** [comment]
Yeap I think this issue is caused by Python 3.7. After switching to Python 3.6 as instructed, the issue is gone. Thanks!
