### ISSUE TITLE
wrong link in docs?

### ISSUE THREAD

**Issue by raybellwaves** [datamllab/tods#4]
![Screenshot from 2020-09-23 22-44-21](https://user-images.githubusercontent.com/17162724/94094810-6b274180-fdee-11ea-91cc-d046a2f49c6e.png)

Says RLCard

**Comment by lhenry15** [comment]
Thanks for letting us know, we will fix it soon

**Comment by lhenry15** [comment]
Problem Fixed, thank you for the reminder!!
[https://tods-doc.github.io/index.html](https://tods-doc.github.io/index.html)
